[package]
name = "gui"
version = "0.1.0"
edition.workspace = true

[dependencies]
egui.version = "0.33.3"
egui_extras = { version = "0.33.3", features = ["default", "image"] }
# eframe = { version = "0.33.3", features = [ "glow" ] }
log = "0.4.29"
env_logger = "0.11.8"
font-kit = "0.14.3"

[dependencies.eframe]
version = "0.33.3"
default-features = false
features = [
"accesskit",
# "default_fonts",
"glow",
"wayland",
"x11"
]
