[package]
name = "rpc"
version = "0.1.0"
edition.workspace = true

[dependencies]
tarpc.workspace = true
serde.workspace = true
strum.workspace = true
uuid.workspace = true
query = { path = "../query", features = ["serde"] }


